class Config(object):
    ELASTICSEARCH_HOST = "localhost"
    MINIMAL_LINE_LENGTH = 25
    JACCARD_THRESHOLD_VALUE = 0.45
    IMAGE_HAMMING_THRESHOLD_VALUE = 0.8
    DICER2_STORAGE_PATH = "./store"
    JOB_PROCESSING_NUM = 4
    ENABLE_CORS = False
    ENABLE_ERROR_TRACEBACK = False
